default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:
  host: localhost

development:
  <<: *default
  database: dandy_software_dev

test:
  <<: *default
  database: dandy_software_test
